/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dialog;

/**
 *
 * @author Gonzalo
 */
public class Ventana2 extends javax.swing.JDialog {

    /**
     * Creates new form Ventana2
     */
    public Ventana2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_Ventana2 = new javax.swing.JLabel();
        jButton1_Ventana4 = new javax.swing.JButton();
        jButton1_Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1_Ventana2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1_Ventana2.setText("VENTANA 2");

        jButton1_Ventana4.setText("Ventana 4");
        jButton1_Ventana4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_Ventana4MouseClicked(evt);
            }
        });

        jButton1_Volver.setText("Volver");
        jButton1_Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_VolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1_Ventana2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton1_Ventana4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jButton1_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1_Ventana2)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_Ventana4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_VolverMouseClicked
        dispose();
    }//GEN-LAST:event_jButton1_VolverMouseClicked

    private void jButton1_Ventana4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_Ventana4MouseClicked
        Ventana4 ventana4 = new Ventana4(this, false);//Se puede hacer poniendo true pero se hace de otra forma
        ventana4.setModalityType(Dialog.ModalityType.TOOLKIT_MODAL);
        ventana4.setVisible(true);
    }//GEN-LAST:event_jButton1_Ventana4MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Ventana4;
    private javax.swing.JButton jButton1_Volver;
    private javax.swing.JLabel jLabel1_Ventana2;
    // End of variables declaration//GEN-END:variables
}
