package GUI;

import GUI.TableModel.ContactosTableModel;
import Logica.LogicaNegocio;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Gonzalo
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        jTableContactos.setModel(new ContactosTableModel(LogicaNegocio.getListaContactos()));
        iniciarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableContactos = new javax.swing.JTable();
        jLabelMensajeError = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAlta = new javax.swing.JMenu();
        jMenuBaja = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTableContactos);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabelMensajeError.setText(" ");
        getContentPane().add(jLabelMensajeError, java.awt.BorderLayout.PAGE_END);

        jMenuAlta.setText("Alta");
        jMenuAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAltaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuAlta);

        jMenuBaja.setText("Baja");
        jMenuBaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBajaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuBaja);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAltaMouseClicked
        jLabelMensajeError.setText("");
        PantallaDarAlta alta = new PantallaDarAlta(this, true);
        alta.setVisible(true);
        refrescar();
    }//GEN-LAST:event_jMenuAltaMouseClicked

    private void jMenuBajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBajaMouseClicked
        jLabelMensajeError.setText("");
        int fila = jTableContactos.getSelectedRow();
        int[] variasFilas = new int[jTableContactos.getSelectedRows().length];
        if (fila == -1) {
            jLabelMensajeError.setText("Error: debes seleccionar una fila para poder dar de baja.");
        } else {
            int cont = 0;
            for (int fila2 : variasFilas) {
                ContactosTableModel ctm = (ContactosTableModel) jTableContactos.getModel();
                ctm.deleteRow(fila - cont);
                cont++;
            }
        }
    }//GEN-LAST:event_jMenuBajaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    public void refrescar() {
        ContactosTableModel ctm = (ContactosTableModel) jTableContactos.getModel();
        ctm.refrescar();
    }

    public void iniciarTabla() {
        ContactosTableModel ctm = new ContactosTableModel(LogicaNegocio.getListaContactos());
        jTableContactos.setModel(ctm);
        //Si no hacemos el punto de ordenar la tabla se podría hacer así:
        //jTableContactos.setModel(new ContactosTableModel(LogicaNegocio.getListaContactos());
        //Para ordenar por campos una tabla:
        TableRowSorter<ContactosTableModel> sorter = new TableRowSorter<>(ctm);
        jTableContactos.setRowSorter(sorter);

        //Para poner un filtro que solo permita añadir cierto tipo de información:
        //por ejemplo que solo se puedan introducir contactos con dni que empiece por 11
        RowFilter<Object, Object> filtro = RowFilter.regexFilter("11", 2);
        sorter.setRowFilter(filtro);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelMensajeError;
    private javax.swing.JMenu jMenuAlta;
    private javax.swing.JMenu jMenuBaja;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableContactos;
    // End of variables declaration//GEN-END:variables
}
