package Agenda.GUI;

import Agenda.GUI.TableModel.IngresoGastoTableModel;
import Agenda.logica.LogicaNegocio;
import java.awt.Color;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Gonzalo
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    double balanceFinal = 0;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        IngresoGastoTableModel ingresoGastoTableModel = new IngresoGastoTableModel(LogicaNegocio.getOperaciones());
        jTable1_Tabla.setModel(ingresoGastoTableModel);
        //Esto es para que ordene la tabla según el campo seleccionado en la cabecera de la tabla.
        TableRowSorter<IngresoGastoTableModel> elQueOrdena = new TableRowSorter<>(ingresoGastoTableModel);
        jTable1_Tabla.setRowSorter(elQueOrdena);
        //Solo deja meter los que empiecen por 0, es decir, si yo meto en la columna 2 algo que no empiece por 0 no me deja añadirlo
        /*RowFilter<Object, Object> expresionRegular = RowFilter.regexFilter("1000", 2);
        elQueOrdena.setRowFilter(expresionRegular);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_Tabla = new javax.swing.JTable();
        jLabel1_Balance = new javax.swing.JLabel();
        jLabel_CampoSacado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1_Alta = new javax.swing.JMenu();
        jMenu_Sacar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1_Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTable1_Tabla);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1_Balance.setText("Balance: ");
        getContentPane().add(jLabel1_Balance, java.awt.BorderLayout.PAGE_END);

        jLabel_CampoSacado.setText(" ");
        getContentPane().add(jLabel_CampoSacado, java.awt.BorderLayout.PAGE_START);

        jMenu1_Alta.setText("Alta");
        jMenu1_Alta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1_AltaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1_Alta);

        jMenu_Sacar.setText("Sacar Campo");
        jMenu_Sacar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_SacarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_Sacar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1_AltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1_AltaMouseClicked
        PantallaDarAlta ingresoGasto = new PantallaDarAlta(this, true);
        ingresoGasto.setVisible(true);
        refrescarTable();
    }//GEN-LAST:event_jMenu1_AltaMouseClicked

    private void jMenu_SacarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_SacarMouseClicked
        
        
        
    }//GEN-LAST:event_jMenu_SacarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1_Balance;
    private javax.swing.JLabel jLabel_CampoSacado;
    private javax.swing.JMenu jMenu1_Alta;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_Sacar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_Tabla;
    // End of variables declaration//GEN-END:variables

    private void refrescarTable() {
        IngresoGastoTableModel igtm = (IngresoGastoTableModel) jTable1_Tabla.getModel();
        igtm.refrescarArray();
    }

    public void establecerBalance(double balance) {
        if (balanceFinal >= 0) {
            balanceFinal = balanceFinal + balance;
            jLabel1_Balance.setText("Balance: " + balanceFinal);
            jLabel1_Balance.setForeground(Color.green);
        } else {
            balanceFinal = balanceFinal + balance;
            jLabel1_Balance.setText("Balance: " + balanceFinal);
            jLabel1_Balance.setForeground(Color.red);
        }
    }
}
