/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Agenda.GUI;

import Agenda.DTO.IngresoGasto;
import Agenda.logica.LogicaNegocio;

/**
 *
 * @author Gonzalo
 */
public class PantallaDarAlta extends javax.swing.JDialog {

    private PantallaPrincipal pPrincipal;
    /**
     * Creates new form PantallaDarAlta
     */
    public PantallaDarAlta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        pPrincipal = (PantallaPrincipal) parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_Fecha = new javax.swing.JLabel();
        jTextField1_Fecha = new javax.swing.JTextField();
        jLabel2_Concepto = new javax.swing.JLabel();
        jLabel3_Importe = new javax.swing.JLabel();
        jTextField2_Concepto = new javax.swing.JTextField();
        jTextField3_Importe = new javax.swing.JTextField();
        jButton1_Aceptar = new javax.swing.JButton();
        jButton2_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1_Fecha.setText("Fecha del ingreso: ");

        jLabel2_Concepto.setText("Concepto");

        jLabel3_Importe.setText("Importe");

        jButton1_Aceptar.setText("Aceptar");
        jButton1_Aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_AceptarMouseClicked(evt);
            }
        });

        jButton2_Cancelar.setText("Cancelar");
        jButton2_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2_CancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1_Fecha)
                    .addComponent(jLabel2_Concepto)
                    .addComponent(jLabel3_Importe)
                    .addComponent(jButton1_Aceptar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2_Cancelar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1_Fecha)
                        .addComponent(jTextField2_Concepto)
                        .addComponent(jTextField3_Importe, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_Fecha)
                    .addComponent(jTextField1_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_Concepto)
                    .addComponent(jTextField2_Concepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3_Importe)
                    .addComponent(jTextField3_Importe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_Aceptar)
                    .addComponent(jButton2_Cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_AceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_AceptarMouseClicked
        IngresoGasto ig = new IngresoGasto(jTextField1_Fecha.getText(), jTextField2_Concepto.getText(), Double.parseDouble(jTextField3_Importe.getText()));
        LogicaNegocio.anadirIngresoGasto(ig);
        double importe = Double.parseDouble(jTextField3_Importe.getText());
        //Para pasar valores a la pantalla principal
        pPrincipal.establecerBalance(importe);
        dispose();
    }//GEN-LAST:event_jButton1_AceptarMouseClicked

    private void jButton2_CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_CancelarMouseClicked
        dispose();
    }//GEN-LAST:event_jButton2_CancelarMouseClicked
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Aceptar;
    private javax.swing.JButton jButton2_Cancelar;
    private javax.swing.JLabel jLabel1_Fecha;
    private javax.swing.JLabel jLabel2_Concepto;
    private javax.swing.JLabel jLabel3_Importe;
    private javax.swing.JTextField jTextField1_Fecha;
    private javax.swing.JTextField jTextField2_Concepto;
    private javax.swing.JTextField jTextField3_Importe;
    // End of variables declaration//GEN-END:variables
}
