package GUI;

import DTOs.Cliente;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Gonzalo
 */
public class JDialogPedirDatos extends javax.swing.JDialog {

    private JFramePrintipal ventanaPrincipal = null;

    /**
     * Creates new form JDialogPedirDatos
     */
    public JDialogPedirDatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        ventanaPrincipal = (JFramePrintipal) parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_Nombre = new javax.swing.JLabel();
        jLabel2_PrimerApellido = new javax.swing.JLabel();
        jLabel3_SegundoApellido = new javax.swing.JLabel();
        jLabel4_DNI = new javax.swing.JLabel();
        jTextField1_SegundoApellido = new javax.swing.JTextField();
        jTextField2_DNI = new javax.swing.JTextField();
        jTextField3_PrimerApellido = new javax.swing.JTextField();
        jTextField4_Nombre = new javax.swing.JTextField();
        jButton1_Aceptar = new javax.swing.JButton();
        jButton1_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1_Nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1_Nombre.setText("Nombre");

        jLabel2_PrimerApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2_PrimerApellido.setText("Primer apellido");

        jLabel3_SegundoApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3_SegundoApellido.setText("Segundo apellido");

        jLabel4_DNI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4_DNI.setText("DNI");

        jButton1_Aceptar.setText("Aceptar");
        jButton1_Aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_AceptarMouseClicked(evt);
            }
        });

        jButton1_Cancelar.setText("Cancelar");
        jButton1_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_CancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1_Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1_Cancelar)
                        .addGap(191, 191, 191))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2_PrimerApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3_SegundoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4_DNI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(56, 56, 56)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField3_PrimerApellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2_DNI)
                            .addComponent(jTextField1_SegundoApellido)
                            .addComponent(jTextField4_Nombre, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField4_Nombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_PrimerApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3_PrimerApellido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3_SegundoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1_SegundoApellido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4_DNI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2_DNI))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_Aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1_Cancelar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_AceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_AceptarMouseClicked
        String nombre = jTextField4_Nombre.getText();
        String apellido1 = jTextField3_PrimerApellido.getText();
        String apellido2 = jTextField1_SegundoApellido.getText();
        String DNI = jTextField2_DNI.getText();
        Cliente cliente = new Cliente(nombre, apellido1, apellido2, DNI);
        ventanaPrincipal.addCliente(cliente);
        dispose();
    }//GEN-LAST:event_jButton1_AceptarMouseClicked

    private void jButton1_CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_CancelarMouseClicked
        dispose();
    }//GEN-LAST:event_jButton1_CancelarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Aceptar;
    private javax.swing.JButton jButton1_Cancelar;
    private javax.swing.JLabel jLabel1_Nombre;
    private javax.swing.JLabel jLabel2_PrimerApellido;
    private javax.swing.JLabel jLabel3_SegundoApellido;
    private javax.swing.JLabel jLabel4_DNI;
    private javax.swing.JTextField jTextField1_SegundoApellido;
    private javax.swing.JTextField jTextField2_DNI;
    private javax.swing.JTextField jTextField3_PrimerApellido;
    private javax.swing.JTextField jTextField4_Nombre;
    // End of variables declaration//GEN-END:variables
}
