package GUI;

import DTOs.Cliente;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gonzalo
 */
public class JFramePrintipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrintipal
     */
    public JFramePrintipal() {
        initComponents();
        inicializarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_MensajeError = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_TablaContactos = new javax.swing.JTable();
        jMenuBar2_MenuAltaBaja = new javax.swing.JMenuBar();
        jMenu3_Alta = new javax.swing.JMenu();
        jMenu4_Baja = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1_MensajeError.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel1_MensajeError, java.awt.BorderLayout.PAGE_END);

        jTable1_TablaContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido1", "Apellido2", "DNI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1_TablaContactos);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu3_Alta.setText("Alta");
        jMenu3_Alta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3_AltaMouseClicked(evt);
            }
        });
        jMenuBar2_MenuAltaBaja.add(jMenu3_Alta);

        jMenu4_Baja.setText("Baja");
        jMenu4_Baja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4_BajaMouseClicked(evt);
            }
        });
        jMenuBar2_MenuAltaBaja.add(jMenu4_Baja);

        setJMenuBar(jMenuBar2_MenuAltaBaja);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3_AltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3_AltaMouseClicked
        jLabel1_MensajeError.setText("");
        JDialogPedirDatos pedirDatos = new JDialogPedirDatos(this, true);
        pedirDatos.setVisible(true);
    }//GEN-LAST:event_jMenu3_AltaMouseClicked

    private void jMenu4_BajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4_BajaMouseClicked
        jLabel1_MensajeError.setText("");
        int fila;
        fila = jTable1_TablaContactos.getSelectedRow();

        int[] variasFilas;
        variasFilas = new int[jTable1_TablaContactos.getSelectedRows().length];

        variasFilas = jTable1_TablaContactos.getSelectedRows();
        if (fila == -1) {
            jLabel1_MensajeError.setText("Selecciona una fila.");
        } else {
            int cont = 0;
            for (int variasFila : variasFilas) {
                DefaultTableModel dtm = (DefaultTableModel) jTable1_TablaContactos.getModel();
                dtm.removeRow(variasFila - cont);
                cont++;
            }
        }
    }//GEN-LAST:event_jMenu4_BajaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrintipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrintipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrintipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrintipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrintipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1_MensajeError;
    private javax.swing.JMenu jMenu3_Alta;
    private javax.swing.JMenu jMenu4_Baja;
    private javax.swing.JMenuBar jMenuBar2_MenuAltaBaja;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_TablaContactos;
    // End of variables declaration//GEN-END:variables

    public void addCliente(Cliente cliente) {
        DefaultTableModel dtm = (DefaultTableModel) jTable1_TablaContactos.getModel();
        dtm.addRow(cliente.clienteArray());
    }

    private void inicializarTabla() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Nombre", "Apellido1", "Apellido2", "DNI"});
        jTable1_TablaContactos.setModel(dtm);
    }
}
