
import javax.swing.JDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gonzalo
 */
public class JFrame_Ejercicio1 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Ejercicio1
     */
    public JFrame_Ejercicio1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1_Sexo = new javax.swing.ButtonGroup();
        jTextField1_Profesion = new javax.swing.JTextField();
        jLabel1_Profesion = new javax.swing.JLabel();
        jLabel1_NHermanos = new javax.swing.JLabel();
        jSpinner1_NHermanos = new javax.swing.JSpinner();
        jLabel2_Edad = new javax.swing.JLabel();
        jComboBox1_Edad = new javax.swing.JComboBox<>();
        jPanel1_Sexo = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jCheckBox1_PracticarDeporte = new javax.swing.JCheckBox();
        jPanel2_QueDeporte = new javax.swing.JPanel();
        jScrollPane1_Deportes = new javax.swing.JScrollPane();
        jList1_Deportes = new javax.swing.JList<>();
        jPanel4_Aficiones = new javax.swing.JPanel();
        jLabel1_Aficiones = new javax.swing.JLabel();
        jLabel1_Compras = new javax.swing.JLabel();
        jSlider1_Compras = new javax.swing.JSlider();
        jLabel2_Television = new javax.swing.JLabel();
        jSlider1_Television = new javax.swing.JSlider();
        jLabel3_Cine = new javax.swing.JLabel();
        jSlider2_Cine = new javax.swing.JSlider();
        jButton1_Aceptar = new javax.swing.JButton();
        jButton2_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1_Profesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_ProfesionActionPerformed(evt);
            }
        });

        jLabel1_Profesion.setText("Profesión:");
        jLabel1_Profesion.setToolTipText("");

        jLabel1_NHermanos.setText("Nº Hermanos");

        jSpinner1_NHermanos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        jSpinner1_NHermanos.setToolTipText("Numero De Hermanos");

        jLabel2_Edad.setText("Edad:");

        jComboBox1_Edad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entre 18 y 30", "Menos de 18", "Mas de 30" }));
        jComboBox1_Edad.setName(""); // NOI18N

        jPanel1_Sexo.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));
        jPanel1_Sexo.setToolTipText("Sexo");

        buttonGroup1_Sexo.add(jRadioButton1);
        jRadioButton1.setText("Hombre");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1_Sexo.add(jRadioButton2);
        jRadioButton2.setText("Mujer");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_SexoLayout = new javax.swing.GroupLayout(jPanel1_Sexo);
        jPanel1_Sexo.setLayout(jPanel1_SexoLayout);
        jPanel1_SexoLayout.setHorizontalGroup(
            jPanel1_SexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_SexoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1_SexoLayout.setVerticalGroup(
            jPanel1_SexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_SexoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1_SexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jCheckBox1_PracticarDeporte.setText("¿Practica algún deporte?");

        jPanel2_QueDeporte.setBorder(javax.swing.BorderFactory.createTitledBorder("¿Cuál?"));

        jList1_Deportes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Tenis", "Fútbol", "Baloncesto", "Rugby", "Ciclismo" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1_Deportes.setViewportView(jList1_Deportes);

        javax.swing.GroupLayout jPanel2_QueDeporteLayout = new javax.swing.GroupLayout(jPanel2_QueDeporte);
        jPanel2_QueDeporte.setLayout(jPanel2_QueDeporteLayout);
        jPanel2_QueDeporteLayout.setHorizontalGroup(
            jPanel2_QueDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1_Deportes)
        );
        jPanel2_QueDeporteLayout.setVerticalGroup(
            jPanel2_QueDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_QueDeporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1_Deportes, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
        );

        jPanel4_Aficiones.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel1_Aficiones.setText("Marque del 1 al 10 su grado de afición a:");

        jLabel1_Compras.setText("Compras: ");

        jSlider1_Compras.setMajorTickSpacing(1);
        jSlider1_Compras.setMaximum(10);
        jSlider1_Compras.setPaintLabels(true);
        jSlider1_Compras.setPaintTicks(true);
        jSlider1_Compras.setToolTipText("Compras");
        jSlider1_Compras.setValue(0);

        jLabel2_Television.setText("Ver Televisión");

        jSlider1_Television.setMajorTickSpacing(1);
        jSlider1_Television.setMaximum(10);
        jSlider1_Television.setPaintLabels(true);
        jSlider1_Television.setPaintTicks(true);
        jSlider1_Television.setToolTipText("Ver Televisión");
        jSlider1_Television.setValue(0);

        jLabel3_Cine.setText("Ir al cine");

        jSlider2_Cine.setMajorTickSpacing(1);
        jSlider2_Cine.setMaximum(10);
        jSlider2_Cine.setPaintLabels(true);
        jSlider2_Cine.setPaintTicks(true);
        jSlider2_Cine.setToolTipText("Ir al cine");
        jSlider2_Cine.setValue(0);

        jButton1_Aceptar.setText("Aceptar");
        jButton1_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_AceptarActionPerformed(evt);
            }
        });

        jButton2_Cancelar.setText("Cancelar");
        jButton2_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4_AficionesLayout = new javax.swing.GroupLayout(jPanel4_Aficiones);
        jPanel4_Aficiones.setLayout(jPanel4_AficionesLayout);
        jPanel4_AficionesLayout.setHorizontalGroup(
            jPanel4_AficionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4_AficionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4_AficionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4_AficionesLayout.createSequentialGroup()
                        .addGroup(jPanel4_AficionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4_AficionesLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1_Compras)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel1_Aficiones, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel4_AficionesLayout.createSequentialGroup()
                        .addGroup(jPanel4_AficionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4_AficionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSlider1_Television, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                .addComponent(jSlider1_Compras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jSlider2_Cine, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4_AficionesLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2_Television)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4_AficionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1_Aceptar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2_Cancelar, javax.swing.GroupLayout.Alignment.TRAILING)))))
            .addGroup(jPanel4_AficionesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3_Cine)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4_AficionesLayout.setVerticalGroup(
            jPanel4_AficionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4_AficionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_Aficiones)
                .addGap(13, 13, 13)
                .addComponent(jLabel1_Compras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4_AficionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4_AficionesLayout.createSequentialGroup()
                        .addComponent(jSlider1_Compras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2_Television)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlider1_Television, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4_AficionesLayout.createSequentialGroup()
                        .addComponent(jButton1_Aceptar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2_Cancelar)
                        .addGap(13, 13, 13)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3_Cine)
                .addGap(9, 9, 9)
                .addComponent(jSlider2_Cine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1_PracticarDeporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2_QueDeporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4_Aficiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1_Profesion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1_Profesion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1_NHermanos, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jSpinner1_NHermanos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_Profesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1_Profesion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_NHermanos)
                    .addComponent(jSpinner1_NHermanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2_Edad)
                    .addComponent(jComboBox1_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1_PracticarDeporte)
                    .addComponent(jPanel2_QueDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jPanel4_Aficiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_ProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_ProfesionActionPerformed
        
    }//GEN-LAST:event_jTextField1_ProfesionActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        //if(jRadioButton1.isEnabled()){
        //    jRadioButton2.setEnabled(false);
        //}
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        //if(jRadioButton2.isEnabled()){
        //    jRadioButton1.setEnabled(false);
        //}
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_AceptarActionPerformed
        PantallaAceptar pantallaSecundaria = new PantallaAceptar();
        pantallaSecundaria.setVisible(true);
    }//GEN-LAST:event_jButton1_AceptarActionPerformed

    private void jButton2_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_CancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton2_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Ejercicio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1_Sexo;
    private javax.swing.JButton jButton1_Aceptar;
    private javax.swing.JButton jButton2_Cancelar;
    private javax.swing.JCheckBox jCheckBox1_PracticarDeporte;
    private javax.swing.JComboBox<String> jComboBox1_Edad;
    private javax.swing.JLabel jLabel1_Aficiones;
    private javax.swing.JLabel jLabel1_Compras;
    private javax.swing.JLabel jLabel1_NHermanos;
    private javax.swing.JLabel jLabel1_Profesion;
    private javax.swing.JLabel jLabel2_Edad;
    private javax.swing.JLabel jLabel2_Television;
    private javax.swing.JLabel jLabel3_Cine;
    private javax.swing.JList<String> jList1_Deportes;
    private javax.swing.JPanel jPanel1_Sexo;
    private javax.swing.JPanel jPanel2_QueDeporte;
    private javax.swing.JPanel jPanel4_Aficiones;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1_Deportes;
    private javax.swing.JSlider jSlider1_Compras;
    private javax.swing.JSlider jSlider1_Television;
    private javax.swing.JSlider jSlider2_Cine;
    private javax.swing.JSpinner jSpinner1_NHermanos;
    private javax.swing.JTextField jTextField1_Profesion;
    // End of variables declaration//GEN-END:variables
}
