/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.DatoValidado;
import GUI.TableModel.ExpresionTableModel;
import Logica.Logica;
import com.easynth.lookandfeel.EaSynthLookAndFeel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Gonzalo
 */
public class JFrameVentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrameVentanaPrincipal
     */
    public JFrameVentanaPrincipal() {
        initComponents();
        cambiarLookAndFeel();
        //centrar ventana en la pantalla
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize(); //recuperamos tamaño pantalla
        int height = pantalla.height;
        int width = pantalla.width;
        setSize(width / 2, height / 2);
        setLocationRelativeTo(null);
        //JAVA HELP
        try {
            File fichero = new File("help" + File.separator + "help_set.hs");
            URL hsURL = fichero.toURI().toURL();
            // Crea el HelpSet y el HelpBroker
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();
            // Pone ayuda a item de menu al pulsarlo.
            hb.enableHelpOnButton(jButtonCambianteAyuda, "principal", helpset);
            hb.enableHelpKey(getRootPane(), "principal", helpset);
        } catch (MalformedURLException ex) {
            Logger.getLogger(JFrameVentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HelpSetException ex) {
            Logger.getLogger(JFrameVentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextFieldDatos.setEditable(false);
    }

    private void cambiarLookAndFeel() {
        try {
            UIManager.setLookAndFeel(EaSynthLookAndFeel.class.getCanonicalName());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Throwable ex) {
            JOptionPane.showInternalMessageDialog(this, "Error al establecer LookAndFeel", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDatos = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonCambianteUno = new GUI.JButtonCambiante();
        jButtonCambianteDos = new GUI.JButtonCambiante();
        jButtonCambianteTres = new GUI.JButtonCambiante();
        jButtonCambianteAyuda = new GUI.JButtonCambiante();
        jButtonCambianteCuatro = new GUI.JButtonCambiante();
        jButtonCambianteCinco = new GUI.JButtonCambiante();
        jButtonCambianteSeis = new GUI.JButtonCambiante();
        jButtonCambianteBorrar = new GUI.JButtonCambiante();
        jButtonCambianteSiete = new GUI.JButtonCambiante();
        jButtonCambianteOcho = new GUI.JButtonCambiante();
        jButtonCambianteNueve = new GUI.JButtonCambiante();
        jButtonCambianteLista = new GUI.JButtonCambiante();
        jButtonCambianteMas = new GUI.JButtonCambiante();
        jButtonCambianteCero = new GUI.JButtonCambiante();
        jButtonCambianteMenos = new GUI.JButtonCambiante();
        jButtonCambianteIgual = new GUI.JButtonCambiante();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(jTextFieldDatos, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(4, 4));

        jButtonCambianteUno.setText("1");
        jButtonCambianteUno.setColorAlPasar(new java.awt.Color(255, 0, 0));
        jButtonCambianteUno.setColorInicial(new java.awt.Color(0, 0, 255));
        jButtonCambianteUno.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButtonCambianteUno.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButtonCambianteUno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambianteUnoMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonCambianteUno);

        jButtonCambianteDos.setText("2");
        jButtonCambianteDos.setColorAlPasar(new java.awt.Color(255, 0, 0));
        jButtonCambianteDos.setColorInicial(new java.awt.Color(0, 0, 255));
        jButtonCambianteDos.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButtonCambianteDos.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButtonCambianteDos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambianteDosMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonCambianteDos);

        jButtonCambianteTres.setText("3");
        jButtonCambianteTres.setColorAlPasar(new java.awt.Color(255, 0, 0));
        jButtonCambianteTres.setColorInicial(new java.awt.Color(0, 0, 255));
        jButtonCambianteTres.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButtonCambianteTres.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButtonCambianteTres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambianteTresMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonCambianteTres);

        jButtonCambianteAyuda.setText("?");
        jButtonCambianteAyuda.setColorAlPasar(new java.awt.Color(255, 255, 0));
        jButtonCambianteAyuda.setColorInicial(new java.awt.Color(0, 0, 255));
        jButtonCambianteAyuda.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButtonCambianteAyuda.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(jButtonCambianteAyuda);

        jButtonCambianteCuatro.setText("4");
        jButtonCambianteCuatro.setColorAlPasar(new java.awt.Color(255, 0, 0));
        jButtonCambianteCuatro.setColorInicial(new java.awt.Color(0, 0, 255));
        jButtonCambianteCuatro.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButtonCambianteCuatro.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButtonCambianteCuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambianteCuatroMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonCambianteCuatro);

        jButtonCambianteCinco.setText("5");
        jButtonCambianteCinco.setColorAlPasar(new java.awt.Color(255, 0, 0));
        jButtonCambianteCinco.setColorInicial(new java.awt.Color(0, 0, 255));
        jButtonCambianteCinco.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButtonCambianteCinco.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButtonCambianteCinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambianteCincoMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonCambianteCinco);

        jButtonCambianteSeis.setText("6");
        jButtonCambianteSeis.setColorAlPasar(new java.awt.Color(255, 0, 0));
        jButtonCambianteSeis.setColorInicial(new java.awt.Color(0, 0, 255));
        jButtonCambianteSeis.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButtonCambianteSeis.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButtonCambianteSeis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambianteSeisMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonCambianteSeis);

        jButtonCambianteBorrar.setText("<");
        jButtonCambianteBorrar.setColorAlPasar(new java.awt.Color(255, 255, 0));
        jButtonCambianteBorrar.setColorInicial(new java.awt.Color(0, 0, 255));
        jButtonCambianteBorrar.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButtonCambianteBorrar.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButtonCambianteBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambianteBorrarMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonCambianteBorrar);

        jButtonCambianteSiete.setText("7");
        jButtonCambianteSiete.setColorAlPasar(new java.awt.Color(255, 0, 0));
        jButtonCambianteSiete.setColorInicial(new java.awt.Color(0, 0, 255));
        jButtonCambianteSiete.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButtonCambianteSiete.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButtonCambianteSiete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambianteSieteMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonCambianteSiete);

        jButtonCambianteOcho.setText("8");
        jButtonCambianteOcho.setColorAlPasar(new java.awt.Color(255, 0, 0));
        jButtonCambianteOcho.setColorInicial(new java.awt.Color(0, 0, 255));
        jButtonCambianteOcho.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButtonCambianteOcho.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButtonCambianteOcho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambianteOchoMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonCambianteOcho);

        jButtonCambianteNueve.setText("9");
        jButtonCambianteNueve.setColorAlPasar(new java.awt.Color(255, 0, 0));
        jButtonCambianteNueve.setColorInicial(new java.awt.Color(0, 0, 255));
        jButtonCambianteNueve.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButtonCambianteNueve.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButtonCambianteNueve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambianteNueveMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonCambianteNueve);

        jButtonCambianteLista.setText("Lista");
        jButtonCambianteLista.setColorAlPasar(new java.awt.Color(0, 255, 255));
        jButtonCambianteLista.setColorInicial(new java.awt.Color(0, 0, 255));
        jButtonCambianteLista.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButtonCambianteLista.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButtonCambianteLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambianteListaMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonCambianteLista);

        jButtonCambianteMas.setText("+");
        jButtonCambianteMas.setColorAlPasar(new java.awt.Color(0, 255, 0));
        jButtonCambianteMas.setColorInicial(new java.awt.Color(0, 0, 255));
        jButtonCambianteMas.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButtonCambianteMas.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButtonCambianteMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambianteMasMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonCambianteMas);

        jButtonCambianteCero.setText("0");
        jButtonCambianteCero.setColorAlPasar(new java.awt.Color(255, 0, 0));
        jButtonCambianteCero.setColorInicial(new java.awt.Color(0, 0, 255));
        jButtonCambianteCero.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButtonCambianteCero.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButtonCambianteCero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambianteCeroMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonCambianteCero);

        jButtonCambianteMenos.setText("-");
        jButtonCambianteMenos.setColorAlPasar(new java.awt.Color(0, 255, 0));
        jButtonCambianteMenos.setColorInicial(new java.awt.Color(0, 0, 255));
        jButtonCambianteMenos.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButtonCambianteMenos.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButtonCambianteMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambianteMenosMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonCambianteMenos);

        jButtonCambianteIgual.setText("=");
        jButtonCambianteIgual.setColorAlPasar(new java.awt.Color(0, 255, 0));
        jButtonCambianteIgual.setColorInicial(new java.awt.Color(0, 0, 255));
        jButtonCambianteIgual.setFuenteAlPasar(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButtonCambianteIgual.setFuenteInicial(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButtonCambianteIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCambianteIgualMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonCambianteIgual);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCambianteUnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambianteUnoMouseClicked
        String cadena = jTextFieldDatos.getText();
        jTextFieldDatos.setText(cadena + "1");
    }//GEN-LAST:event_jButtonCambianteUnoMouseClicked

    private void jButtonCambianteDosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambianteDosMouseClicked
        String cadena = jTextFieldDatos.getText();
        jTextFieldDatos.setText(cadena + "2");
    }//GEN-LAST:event_jButtonCambianteDosMouseClicked

    private void jButtonCambianteTresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambianteTresMouseClicked
        String cadena = jTextFieldDatos.getText();
        jTextFieldDatos.setText(cadena + "3");
    }//GEN-LAST:event_jButtonCambianteTresMouseClicked

    private void jButtonCambianteCuatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambianteCuatroMouseClicked
        String cadena = jTextFieldDatos.getText();
        jTextFieldDatos.setText(cadena + "4");
    }//GEN-LAST:event_jButtonCambianteCuatroMouseClicked

    private void jButtonCambianteCincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambianteCincoMouseClicked
        String cadena = jTextFieldDatos.getText();
        jTextFieldDatos.setText(cadena + "5");
    }//GEN-LAST:event_jButtonCambianteCincoMouseClicked

    private void jButtonCambianteSeisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambianteSeisMouseClicked
        String cadena = jTextFieldDatos.getText();
        jTextFieldDatos.setText(cadena + "6");
    }//GEN-LAST:event_jButtonCambianteSeisMouseClicked

    private void jButtonCambianteSieteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambianteSieteMouseClicked
        String cadena = jTextFieldDatos.getText();
        jTextFieldDatos.setText(cadena + "7");
    }//GEN-LAST:event_jButtonCambianteSieteMouseClicked

    private void jButtonCambianteOchoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambianteOchoMouseClicked
        String cadena = jTextFieldDatos.getText();
        jTextFieldDatos.setText(cadena + "8");
    }//GEN-LAST:event_jButtonCambianteOchoMouseClicked

    private void jButtonCambianteNueveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambianteNueveMouseClicked
        String cadena = jTextFieldDatos.getText();
        jTextFieldDatos.setText(cadena + "9");
    }//GEN-LAST:event_jButtonCambianteNueveMouseClicked

    private void jButtonCambianteMasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambianteMasMouseClicked
        String cadena = jTextFieldDatos.getText();
        jTextFieldDatos.setText(cadena + "+");
    }//GEN-LAST:event_jButtonCambianteMasMouseClicked

    private void jButtonCambianteCeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambianteCeroMouseClicked
        String cadena = jTextFieldDatos.getText();
        jTextFieldDatos.setText(cadena + "0");
    }//GEN-LAST:event_jButtonCambianteCeroMouseClicked

    private void jButtonCambianteMenosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambianteMenosMouseClicked
        String cadena = jTextFieldDatos.getText();
        jTextFieldDatos.setText(cadena + "-");
    }//GEN-LAST:event_jButtonCambianteMenosMouseClicked

    private void jButtonCambianteBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambianteBorrarMouseClicked
        String cadena = jTextFieldDatos.getText();
        String nuevo = "";
        for (int i = 1; i < cadena.length(); i++) {
            nuevo += cadena.charAt(i - 1);
        }
        jTextFieldDatos.setText(nuevo);
    }//GEN-LAST:event_jButtonCambianteBorrarMouseClicked

    private void jButtonCambianteListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambianteListaMouseClicked

        JDialogTablaExpresionCorrecta tabla = new JDialogTablaExpresionCorrecta(this, false);
        tabla.setVisible(true);

    }//GEN-LAST:event_jButtonCambianteListaMouseClicked

    private void jButtonCambianteIgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCambianteIgualMouseClicked
        if (!Pattern.matches("^-?[0-9]+[+-]+[0-9]+", jTextFieldDatos.getText())) {
            evt.consume();
            JOptionPane.showMessageDialog(this,"Se procede a guardar en la lista de operaciones","Expresión correcta",JOptionPane.ERROR_MESSAGE);
            Date fecha = new Date();
            String hora = fecha.getHours() + ":" + fecha.getMinutes() + ":" + fecha.getSeconds();
            String expresion = jTextFieldDatos.getText();
            DatoValidado dato = new DatoValidado(fecha, hora, expresion);
            Logica.addDato(dato);
        } else {
            JOptionPane.showMessageDialog(this,"Expresión incorrecta","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCambianteIgualMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            //java.util.ljTextFieldDATOSer.getLogger(JFrameVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameVentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.JButtonCambiante jButtonCambianteAyuda;
    private GUI.JButtonCambiante jButtonCambianteBorrar;
    private GUI.JButtonCambiante jButtonCambianteCero;
    private GUI.JButtonCambiante jButtonCambianteCinco;
    private GUI.JButtonCambiante jButtonCambianteCuatro;
    private GUI.JButtonCambiante jButtonCambianteDos;
    private GUI.JButtonCambiante jButtonCambianteIgual;
    private GUI.JButtonCambiante jButtonCambianteLista;
    private GUI.JButtonCambiante jButtonCambianteMas;
    private GUI.JButtonCambiante jButtonCambianteMenos;
    private GUI.JButtonCambiante jButtonCambianteNueve;
    private GUI.JButtonCambiante jButtonCambianteOcho;
    private GUI.JButtonCambiante jButtonCambianteSeis;
    private GUI.JButtonCambiante jButtonCambianteSiete;
    private GUI.JButtonCambiante jButtonCambianteTres;
    private GUI.JButtonCambiante jButtonCambianteUno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldDatos;
    // End of variables declaration//GEN-END:variables
}
